var annotated_dup =
[
    [ "CLI", "namespace_c_l_i.html", [
      [ "detail", "namespace_c_l_i_1_1detail.html", [
        [ "element_type", "struct_c_l_i_1_1detail_1_1element__type.html", "struct_c_l_i_1_1detail_1_1element__type" ],
        [ "element_type&lt; T, typename std::enable_if&lt; is_copyable_ptr&lt; T &gt;::value &gt;::type &gt;", "struct_c_l_i_1_1detail_1_1element__type_3_01_t_00_01typename_01std_1_1enable__if_3_01is__copyablcf4068753293666f52fa2143458d7e20.html", "struct_c_l_i_1_1detail_1_1element__type_3_01_t_00_01typename_01std_1_1enable__if_3_01is__copyablcf4068753293666f52fa2143458d7e20" ],
        [ "element_value_type", "struct_c_l_i_1_1detail_1_1element__value__type.html", "struct_c_l_i_1_1detail_1_1element__value__type" ],
        [ "pair_adaptor", "struct_c_l_i_1_1detail_1_1pair__adaptor.html", "struct_c_l_i_1_1detail_1_1pair__adaptor" ],
        [ "pair_adaptor&lt; T, conditional_t&lt; false, void_t&lt; typename T::value_type::first_type, typename T::value_type::second_type &gt;, void &gt; &gt;", "struct_c_l_i_1_1detail_1_1pair__adaptor_3_01_t_00_01conditional__t_3_01false_00_01void__t_3_01ty57376c4a6f008b828f6707df132586d8.html", "struct_c_l_i_1_1detail_1_1pair__adaptor_3_01_t_00_01conditional__t_3_01false_00_01void__t_3_01ty57376c4a6f008b828f6707df132586d8" ],
        [ "is_direct_constructible", "class_c_l_i_1_1detail_1_1is__direct__constructible.html", "class_c_l_i_1_1detail_1_1is__direct__constructible" ],
        [ "is_ostreamable", "class_c_l_i_1_1detail_1_1is__ostreamable.html", "class_c_l_i_1_1detail_1_1is__ostreamable" ],
        [ "is_istreamable", "class_c_l_i_1_1detail_1_1is__istreamable.html", "class_c_l_i_1_1detail_1_1is__istreamable" ],
        [ "is_complex", "class_c_l_i_1_1detail_1_1is__complex.html", "class_c_l_i_1_1detail_1_1is__complex" ],
        [ "is_mutable_container", "struct_c_l_i_1_1detail_1_1is__mutable__container.html", null ],
        [ "is_mutable_container&lt; T, conditional_t&lt; false, void_t&lt; typename T::value_type, decltype(std::declval&lt; T &gt;().end()), decltype(std::declval&lt; T &gt;().clear()), decltype(std::declval&lt; T &gt;().insert(std::declval&lt; decltype(std::declval&lt; T &gt;().end())&gt;(), std::declval&lt; const typename T::value_type &amp; &gt;()))&gt;, void &gt; &gt;", "struct_c_l_i_1_1detail_1_1is__mutable__container_3_01_t_00_01conditional__t_3_01false_00_01void_9711c92f16061f5742bb50eefb1b0c0c.html", null ],
        [ "is_readable_container", "struct_c_l_i_1_1detail_1_1is__readable__container.html", null ],
        [ "is_readable_container&lt; T, conditional_t&lt; false, void_t&lt; decltype(std::declval&lt; T &gt;().end()), decltype(std::declval&lt; T &gt;().begin())&gt;, void &gt; &gt;", "struct_c_l_i_1_1detail_1_1is__readable__container_3_01_t_00_01conditional__t_3_01false_00_01void1b163ef1438ddc3089d5e11b3b2b1293.html", null ],
        [ "is_wrapper", "struct_c_l_i_1_1detail_1_1is__wrapper.html", null ],
        [ "is_wrapper&lt; T, conditional_t&lt; false, void_t&lt; typename T::value_type &gt;, void &gt; &gt;", "struct_c_l_i_1_1detail_1_1is__wrapper_3_01_t_00_01conditional__t_3_01false_00_01void__t_3_01type256f69b9a9ada1608beb2e1e7b0f6f4c.html", null ],
        [ "is_tuple_like", "class_c_l_i_1_1detail_1_1is__tuple__like.html", "class_c_l_i_1_1detail_1_1is__tuple__like" ],
        [ "type_count_base", "struct_c_l_i_1_1detail_1_1type__count__base.html", "struct_c_l_i_1_1detail_1_1type__count__base" ],
        [ "type_count_base&lt; T, typename std::enable_if&lt;!is_tuple_like&lt; T &gt;::value &amp;&amp;!is_mutable_container&lt; T &gt;::value &amp;&amp;!std::is_void&lt; T &gt;::value &gt;::type &gt;", "struct_c_l_i_1_1detail_1_1type__count__base_3_01_t_00_01typename_01std_1_1enable__if_3_9is__tupl1d95856913595d9d18df1e9b7db10a2c.html", "struct_c_l_i_1_1detail_1_1type__count__base_3_01_t_00_01typename_01std_1_1enable__if_3_9is__tupl1d95856913595d9d18df1e9b7db10a2c" ],
        [ "type_count_base&lt; T, typename std::enable_if&lt; is_tuple_like&lt; T &gt;::value &amp;&amp;!is_mutable_container&lt; T &gt;::value &gt;::type &gt;", "struct_c_l_i_1_1detail_1_1type__count__base_3_01_t_00_01typename_01std_1_1enable__if_3_01is__tup573c8f6a452dc2b871d7cd3189dda714.html", "struct_c_l_i_1_1detail_1_1type__count__base_3_01_t_00_01typename_01std_1_1enable__if_3_01is__tup573c8f6a452dc2b871d7cd3189dda714" ],
        [ "type_count_base&lt; T, typename std::enable_if&lt; is_mutable_container&lt; T &gt;::value &gt;::type &gt;", "struct_c_l_i_1_1detail_1_1type__count__base_3_01_t_00_01typename_01std_1_1enable__if_3_01is__mut25537d1dbe2209c0fb1d9a95e46a36a7.html", "struct_c_l_i_1_1detail_1_1type__count__base_3_01_t_00_01typename_01std_1_1enable__if_3_01is__mut25537d1dbe2209c0fb1d9a95e46a36a7" ],
        [ "wrapped_type", "struct_c_l_i_1_1detail_1_1wrapped__type.html", "struct_c_l_i_1_1detail_1_1wrapped__type" ],
        [ "wrapped_type&lt; T, def, typename std::enable_if&lt; is_wrapper&lt; T &gt;::value &gt;::type &gt;", "struct_c_l_i_1_1detail_1_1wrapped__type_3_01_t_00_01def_00_01typename_01std_1_1enable__if_3_01isa724b5b3d1f263241cafc27a49bae246.html", "struct_c_l_i_1_1detail_1_1wrapped__type_3_01_t_00_01def_00_01typename_01std_1_1enable__if_3_01isa724b5b3d1f263241cafc27a49bae246" ],
        [ "subtype_count", "struct_c_l_i_1_1detail_1_1subtype__count.html", null ],
        [ "subtype_count_min", "struct_c_l_i_1_1detail_1_1subtype__count__min.html", null ],
        [ "type_count", "struct_c_l_i_1_1detail_1_1type__count.html", "struct_c_l_i_1_1detail_1_1type__count" ],
        [ "type_count&lt; T, typename std::enable_if&lt;!is_wrapper&lt; T &gt;::value &amp;&amp;!is_tuple_like&lt; T &gt;::value &amp;&amp;!is_complex&lt; T &gt;::value &amp;&amp;!std::is_void&lt; T &gt;::value &gt;::type &gt;", "struct_c_l_i_1_1detail_1_1type__count_3_01_t_00_01typename_01std_1_1enable__if_3_9is__wrapper_3_b01f5ffbc1be4715e41384ef05a4c2a6.html", "struct_c_l_i_1_1detail_1_1type__count_3_01_t_00_01typename_01std_1_1enable__if_3_9is__wrapper_3_b01f5ffbc1be4715e41384ef05a4c2a6" ],
        [ "type_count&lt; T, typename std::enable_if&lt; is_complex&lt; T &gt;::value &gt;::type &gt;", "struct_c_l_i_1_1detail_1_1type__count_3_01_t_00_01typename_01std_1_1enable__if_3_01is__complex_31fac009dcf70627e04f80462c5d88ca8.html", "struct_c_l_i_1_1detail_1_1type__count_3_01_t_00_01typename_01std_1_1enable__if_3_01is__complex_31fac009dcf70627e04f80462c5d88ca8" ],
        [ "type_count&lt; T, typename std::enable_if&lt; is_mutable_container&lt; T &gt;::value &gt;::type &gt;", "struct_c_l_i_1_1detail_1_1type__count_3_01_t_00_01typename_01std_1_1enable__if_3_01is__mutable__cb200eb27fab347649b083951e77032e.html", "struct_c_l_i_1_1detail_1_1type__count_3_01_t_00_01typename_01std_1_1enable__if_3_01is__mutable__cb200eb27fab347649b083951e77032e" ],
        [ "type_count&lt; T, typename std::enable_if&lt; is_wrapper&lt; T &gt;::value &amp;&amp;!is_complex&lt; T &gt;::value &amp;&amp;!is_tuple_like&lt; T &gt;::value &amp;&amp;!is_mutable_container&lt; T &gt;::value &gt;::type &gt;", "struct_c_l_i_1_1detail_1_1type__count_3_01_t_00_01typename_01std_1_1enable__if_3_01is__wrapper_39a4e337a2aa393bb8556b7ab15846b8b.html", "struct_c_l_i_1_1detail_1_1type__count_3_01_t_00_01typename_01std_1_1enable__if_3_01is__wrapper_39a4e337a2aa393bb8556b7ab15846b8b" ],
        [ "ExistingFileValidator", "class_c_l_i_1_1detail_1_1_existing_file_validator.html", "class_c_l_i_1_1detail_1_1_existing_file_validator" ],
        [ "ExistingDirectoryValidator", "class_c_l_i_1_1detail_1_1_existing_directory_validator.html", "class_c_l_i_1_1detail_1_1_existing_directory_validator" ],
        [ "ExistingPathValidator", "class_c_l_i_1_1detail_1_1_existing_path_validator.html", "class_c_l_i_1_1detail_1_1_existing_path_validator" ],
        [ "NonexistentPathValidator", "class_c_l_i_1_1detail_1_1_nonexistent_path_validator.html", "class_c_l_i_1_1detail_1_1_nonexistent_path_validator" ],
        [ "IPV4Validator", "class_c_l_i_1_1detail_1_1_i_p_v4_validator.html", "class_c_l_i_1_1detail_1_1_i_p_v4_validator" ],
        [ "EscapedStringTransformer", "class_c_l_i_1_1detail_1_1_escaped_string_transformer.html", "class_c_l_i_1_1detail_1_1_escaped_string_transformer" ],
        [ "has_find", "struct_c_l_i_1_1detail_1_1has__find.html", "struct_c_l_i_1_1detail_1_1has__find" ],
        [ "AppFriend", "struct_c_l_i_1_1detail_1_1_app_friend.html", "struct_c_l_i_1_1detail_1_1_app_friend" ]
      ] ],
      [ "adl_detail", "namespace_c_l_i_1_1adl__detail.html", [
        [ "is_lexical_castable", "class_c_l_i_1_1adl__detail_1_1is__lexical__castable.html", "class_c_l_i_1_1adl__detail_1_1is__lexical__castable" ]
      ] ],
      [ "Error", "class_c_l_i_1_1_error.html", "class_c_l_i_1_1_error" ],
      [ "ConstructionError", "class_c_l_i_1_1_construction_error.html", null ],
      [ "IncorrectConstruction", "class_c_l_i_1_1_incorrect_construction.html", "class_c_l_i_1_1_incorrect_construction" ],
      [ "BadNameString", "class_c_l_i_1_1_bad_name_string.html", "class_c_l_i_1_1_bad_name_string" ],
      [ "OptionAlreadyAdded", "class_c_l_i_1_1_option_already_added.html", "class_c_l_i_1_1_option_already_added" ],
      [ "ParseError", "class_c_l_i_1_1_parse_error.html", null ],
      [ "Success", "class_c_l_i_1_1_success.html", "class_c_l_i_1_1_success" ],
      [ "CallForHelp", "class_c_l_i_1_1_call_for_help.html", "class_c_l_i_1_1_call_for_help" ],
      [ "CallForAllHelp", "class_c_l_i_1_1_call_for_all_help.html", "class_c_l_i_1_1_call_for_all_help" ],
      [ "CallForVersion", "class_c_l_i_1_1_call_for_version.html", "class_c_l_i_1_1_call_for_version" ],
      [ "RuntimeError", "class_c_l_i_1_1_runtime_error.html", "class_c_l_i_1_1_runtime_error" ],
      [ "FileError", "class_c_l_i_1_1_file_error.html", "class_c_l_i_1_1_file_error" ],
      [ "ConversionError", "class_c_l_i_1_1_conversion_error.html", "class_c_l_i_1_1_conversion_error" ],
      [ "ValidationError", "class_c_l_i_1_1_validation_error.html", "class_c_l_i_1_1_validation_error" ],
      [ "RequiredError", "class_c_l_i_1_1_required_error.html", "class_c_l_i_1_1_required_error" ],
      [ "ArgumentMismatch", "class_c_l_i_1_1_argument_mismatch.html", "class_c_l_i_1_1_argument_mismatch" ],
      [ "RequiresError", "class_c_l_i_1_1_requires_error.html", "class_c_l_i_1_1_requires_error" ],
      [ "ExcludesError", "class_c_l_i_1_1_excludes_error.html", "class_c_l_i_1_1_excludes_error" ],
      [ "ExtrasError", "class_c_l_i_1_1_extras_error.html", "class_c_l_i_1_1_extras_error" ],
      [ "ConfigError", "class_c_l_i_1_1_config_error.html", "class_c_l_i_1_1_config_error" ],
      [ "InvalidError", "class_c_l_i_1_1_invalid_error.html", "class_c_l_i_1_1_invalid_error" ],
      [ "HorribleError", "class_c_l_i_1_1_horrible_error.html", null ],
      [ "OptionNotFound", "class_c_l_i_1_1_option_not_found.html", "class_c_l_i_1_1_option_not_found" ],
      [ "make_void", "struct_c_l_i_1_1make__void.html", "struct_c_l_i_1_1make__void" ],
      [ "is_bool", "struct_c_l_i_1_1is__bool.html", null ],
      [ "is_bool&lt; bool &gt;", "struct_c_l_i_1_1is__bool_3_01bool_01_4.html", null ],
      [ "is_shared_ptr", "struct_c_l_i_1_1is__shared__ptr.html", null ],
      [ "is_shared_ptr&lt; std::shared_ptr&lt; T &gt; &gt;", "struct_c_l_i_1_1is__shared__ptr_3_01std_1_1shared__ptr_3_01_t_01_4_01_4.html", null ],
      [ "is_shared_ptr&lt; const std::shared_ptr&lt; T &gt; &gt;", "struct_c_l_i_1_1is__shared__ptr_3_01const_01std_1_1shared__ptr_3_01_t_01_4_01_4.html", null ],
      [ "is_copyable_ptr", "struct_c_l_i_1_1is__copyable__ptr.html", "struct_c_l_i_1_1is__copyable__ptr" ],
      [ "IsMemberType", "struct_c_l_i_1_1_is_member_type.html", "struct_c_l_i_1_1_is_member_type" ],
      [ "IsMemberType&lt; const char * &gt;", "struct_c_l_i_1_1_is_member_type_3_01const_01char_01_5_01_4.html", "struct_c_l_i_1_1_is_member_type_3_01const_01char_01_5_01_4" ],
      [ "ConfigItem", "struct_c_l_i_1_1_config_item.html", "struct_c_l_i_1_1_config_item" ],
      [ "Config", "class_c_l_i_1_1_config.html", "class_c_l_i_1_1_config" ],
      [ "ConfigBase", "class_c_l_i_1_1_config_base.html", "class_c_l_i_1_1_config_base" ],
      [ "ConfigINI", "class_c_l_i_1_1_config_i_n_i.html", "class_c_l_i_1_1_config_i_n_i" ],
      [ "Validator", "class_c_l_i_1_1_validator.html", "class_c_l_i_1_1_validator" ],
      [ "CustomValidator", "class_c_l_i_1_1_custom_validator.html", null ],
      [ "TypeValidator", "class_c_l_i_1_1_type_validator.html", "class_c_l_i_1_1_type_validator" ],
      [ "FileOnDefaultPath", "class_c_l_i_1_1_file_on_default_path.html", "class_c_l_i_1_1_file_on_default_path" ],
      [ "Range", "class_c_l_i_1_1_range.html", "class_c_l_i_1_1_range" ],
      [ "Bound", "class_c_l_i_1_1_bound.html", "class_c_l_i_1_1_bound" ],
      [ "IsMember", "class_c_l_i_1_1_is_member.html", "class_c_l_i_1_1_is_member" ],
      [ "Transformer", "class_c_l_i_1_1_transformer.html", "class_c_l_i_1_1_transformer" ],
      [ "CheckedTransformer", "class_c_l_i_1_1_checked_transformer.html", "class_c_l_i_1_1_checked_transformer" ],
      [ "AsNumberWithUnit", "class_c_l_i_1_1_as_number_with_unit.html", "class_c_l_i_1_1_as_number_with_unit" ],
      [ "AsSizeValue", "class_c_l_i_1_1_as_size_value.html", "class_c_l_i_1_1_as_size_value" ],
      [ "FormatterBase", "class_c_l_i_1_1_formatter_base.html", "class_c_l_i_1_1_formatter_base" ],
      [ "FormatterLambda", "class_c_l_i_1_1_formatter_lambda.html", "class_c_l_i_1_1_formatter_lambda" ],
      [ "Formatter", "class_c_l_i_1_1_formatter.html", "class_c_l_i_1_1_formatter" ],
      [ "OptionBase", "class_c_l_i_1_1_option_base.html", "class_c_l_i_1_1_option_base" ],
      [ "OptionDefaults", "class_c_l_i_1_1_option_defaults.html", "class_c_l_i_1_1_option_defaults" ],
      [ "Option", "class_c_l_i_1_1_option.html", "class_c_l_i_1_1_option" ],
      [ "App", "class_c_l_i_1_1_app.html", "class_c_l_i_1_1_app" ],
      [ "Option_group", "class_c_l_i_1_1_option__group.html", "class_c_l_i_1_1_option__group" ]
    ] ],
    [ "wfa", "namespacewfa.html", [
      [ "WFAligner", "classwfa_1_1_w_f_aligner.html", "classwfa_1_1_w_f_aligner" ],
      [ "WFAlignerIndel", "classwfa_1_1_w_f_aligner_indel.html", "classwfa_1_1_w_f_aligner_indel" ],
      [ "WFAlignerEdit", "classwfa_1_1_w_f_aligner_edit.html", "classwfa_1_1_w_f_aligner_edit" ],
      [ "WFAlignerGapLinear", "classwfa_1_1_w_f_aligner_gap_linear.html", "classwfa_1_1_w_f_aligner_gap_linear" ],
      [ "WFAlignerGapAffine", "classwfa_1_1_w_f_aligner_gap_affine.html", "classwfa_1_1_w_f_aligner_gap_affine" ],
      [ "WFAlignerGapAffine2Pieces", "classwfa_1_1_w_f_aligner_gap_affine2_pieces.html", "classwfa_1_1_w_f_aligner_gap_affine2_pieces" ]
    ] ],
    [ "__attribute__", "struct____attribute____.html", "struct____attribute____" ],
    [ "_wavefront_aligner_t", "struct__wavefront__aligner__t.html", "struct__wavefront__aligner__t" ],
    [ "affine2p_cell_t", "structaffine2p__cell__t.html", "structaffine2p__cell__t" ],
    [ "affine2p_matrix_t", "structaffine2p__matrix__t.html", "structaffine2p__matrix__t" ],
    [ "affine2p_penalties_t", "structaffine2p__penalties__t.html", "structaffine2p__penalties__t" ],
    [ "affine_cell_t", "structaffine__cell__t.html", "structaffine__cell__t" ],
    [ "affine_matrix_t", "structaffine__matrix__t.html", "structaffine__matrix__t" ],
    [ "affine_penalties_t", "structaffine__penalties__t.html", "structaffine__penalties__t" ],
    [ "align_bench_params_t", "structalign__bench__params__t.html", "structalign__bench__params__t" ],
    [ "align_input_t", "structalign__input__t.html", "structalign__input__t" ],
    [ "alignment_form_t", "structalignment__form__t.html", "structalignment__form__t" ],
    [ "alignment_system_t", "structalignment__system__t.html", "structalignment__system__t" ],
    [ "bitmap_block_t", "structbitmap__block__t.html", "structbitmap__block__t" ],
    [ "bitmap_t", "structbitmap__t.html", "structbitmap__t" ],
    [ "bpm_matrix_t", "structbpm__matrix__t.html", "structbpm__matrix__t" ],
    [ "bpm_pattern_t", "structbpm__pattern__t.html", "structbpm__pattern__t" ],
    [ "cigar_t", "structcigar__t.html", "structcigar__t" ],
    [ "CommandParser", "class_command_parser.html", "class_command_parser" ],
    [ "ConvertArgs", "struct_convert_args.html", "struct_convert_args" ],
    [ "countour_bench_args", "structcountour__bench__args.html", "structcountour__bench__args" ],
    [ "GFA", "class_g_f_a.html", "class_g_f_a" ],
    [ "heatmap_t", "structheatmap__t.html", "structheatmap__t" ],
    [ "IndexArgs", "struct_index_args.html", "struct_index_args" ],
    [ "ksw_extz_t", "structksw__extz__t.html", "structksw__extz__t" ],
    [ "linear_penalties_t", "structlinear__penalties__t.html", "structlinear__penalties__t" ],
    [ "LinksSet", "class_links_set.html", "class_links_set" ],
    [ "match_function_params_t", "structmatch__function__params__t.html", "structmatch__function__params__t" ],
    [ "MergeArgs", "struct_merge_args.html", "struct_merge_args" ],
    [ "Minimizer", "class_minimizer.html", "class_minimizer" ],
    [ "MinimizerSet", "class_minimizer_set.html", "class_minimizer_set" ],
    [ "mm_allocator_reference_t", "structmm__allocator__reference__t.html", "structmm__allocator__reference__t" ],
    [ "mm_allocator_request_t", "structmm__allocator__request__t.html", "structmm__allocator__request__t" ],
    [ "mm_allocator_segment_t", "structmm__allocator__segment__t.html", "structmm__allocator__segment__t" ],
    [ "mm_allocator_t", "structmm__allocator__t.html", "structmm__allocator__t" ],
    [ "mm_malloc_request_t", "structmm__malloc__request__t.html", "structmm__malloc__request__t" ],
    [ "mm_stack_segment_t", "structmm__stack__segment__t.html", "structmm__stack__segment__t" ],
    [ "mm_stack_state_t", "structmm__stack__state__t.html", "structmm__stack__state__t" ],
    [ "mm_stack_t", "structmm__stack__t.html", "structmm__stack__t" ],
    [ "Path", "class_path.html", "class_path" ],
    [ "pcigar_op_t", "structpcigar__op__t.html", "structpcigar__op__t" ],
    [ "profiler_counter_t", "structprofiler__counter__t.html", "structprofiler__counter__t" ],
    [ "profiler_rcounter_t", "structprofiler__rcounter__t.html", "structprofiler__rcounter__t" ],
    [ "profiler_timer_t", "structprofiler__timer__t.html", "structprofiler__timer__t" ],
    [ "score_matrix_t", "structscore__matrix__t.html", "structscore__matrix__t" ],
    [ "Segment", "class_segment.html", "class_segment" ],
    [ "seq_error_t", "structseq__error__t.html", "structseq__error__t" ],
    [ "sequence_buffer_t", "structsequence__buffer__t.html", "structsequence__buffer__t" ],
    [ "sequence_offset_t", "structsequence__offset__t.html", "structsequence__offset__t" ],
    [ "vector_t", "structvector__t.html", "structvector__t" ],
    [ "ViewArgs", "struct_view_args.html", "struct_view_args" ],
    [ "Walk", "class_walk.html", "class_walk" ],
    [ "wavefront_align_status_t", "structwavefront__align__status__t.html", "structwavefront__align__status__t" ],
    [ "wavefront_aligner_attr_t", "structwavefront__aligner__attr__t.html", "structwavefront__aligner__attr__t" ],
    [ "wavefront_bialigner_t", "structwavefront__bialigner__t.html", "structwavefront__bialigner__t" ],
    [ "wavefront_components_t", "structwavefront__components__t.html", "structwavefront__components__t" ],
    [ "wavefront_heuristic_t", "structwavefront__heuristic__t.html", "structwavefront__heuristic__t" ],
    [ "wavefront_penalties_t", "structwavefront__penalties__t.html", "structwavefront__penalties__t" ],
    [ "wavefront_plot_attr_t", "structwavefront__plot__attr__t.html", "structwavefront__plot__attr__t" ],
    [ "wavefront_plot_t", "structwavefront__plot__t.html", "structwavefront__plot__t" ],
    [ "wavefront_pos_t", "structwavefront__pos__t.html", "structwavefront__pos__t" ],
    [ "wavefront_sequences_t", "structwavefront__sequences__t.html", "structwavefront__sequences__t" ],
    [ "wavefront_set_t", "structwavefront__set__t.html", "structwavefront__set__t" ],
    [ "wavefront_slab_t", "structwavefront__slab__t.html", "structwavefront__slab__t" ],
    [ "wavefront_t", "structwavefront__t.html", "structwavefront__t" ],
    [ "wf_backtrace_buffer_t", "structwf__backtrace__buffer__t.html", "structwf__backtrace__buffer__t" ],
    [ "wf_backtrace_init_pos_t", "structwf__backtrace__init__pos__t.html", "structwf__backtrace__init__pos__t" ],
    [ "wf_bialign_breakpoint_t", "structwf__bialign__breakpoint__t.html", "structwf__bialign__breakpoint__t" ]
];