var hierarchy =
[
    [ "__attribute__", "struct____attribute____.html", null ],
    [ "_wavefront_aligner_t", "struct__wavefront__aligner__t.html", null ],
    [ "affine2p_cell_t", "structaffine2p__cell__t.html", null ],
    [ "affine2p_matrix_t", "structaffine2p__matrix__t.html", null ],
    [ "affine2p_penalties_t", "structaffine2p__penalties__t.html", null ],
    [ "affine_cell_t", "structaffine__cell__t.html", null ],
    [ "affine_matrix_t", "structaffine__matrix__t.html", null ],
    [ "affine_penalties_t", "structaffine__penalties__t.html", null ],
    [ "align_bench_params_t", "structalign__bench__params__t.html", null ],
    [ "align_input_t", "structalign__input__t.html", null ],
    [ "alignment_form_t", "structalignment__form__t.html", null ],
    [ "alignment_system_t", "structalignment__system__t.html", null ],
    [ "CLI::App", "class_c_l_i_1_1_app.html", [
      [ "CLI::Option_group", "class_c_l_i_1_1_option__group.html", null ]
    ] ],
    [ "CLI::detail::AppFriend", "struct_c_l_i_1_1detail_1_1_app_friend.html", null ],
    [ "bitmap_block_t", "structbitmap__block__t.html", null ],
    [ "bitmap_t", "structbitmap__t.html", null ],
    [ "bpm_matrix_t", "structbpm__matrix__t.html", null ],
    [ "bpm_pattern_t", "structbpm__pattern__t.html", null ],
    [ "cigar_t", "structcigar__t.html", null ],
    [ "CommandParser", "class_command_parser.html", null ],
    [ "conditional_t", null, [
      [ "CLI::detail::is_mutable_container< T, conditional_t< false, void_t< typename T::value_type, decltype(std::declval< T >().end()), decltype(std::declval< T >().clear()), decltype(std::declval< T >().insert(std::declval< decltype(std::declval< T >().end())>(), std::declval< const typename T::value_type & >()))>, void > >", "struct_c_l_i_1_1detail_1_1is__mutable__container_3_01_t_00_01conditional__t_3_01false_00_01void_9711c92f16061f5742bb50eefb1b0c0c.html", null ]
    ] ],
    [ "CLI::Config", "class_c_l_i_1_1_config.html", [
      [ "CLI::ConfigBase", "class_c_l_i_1_1_config_base.html", [
        [ "CLI::ConfigINI", "class_c_l_i_1_1_config_i_n_i.html", null ]
      ] ]
    ] ],
    [ "CLI::ConfigItem", "struct_c_l_i_1_1_config_item.html", null ],
    [ "ConvertArgs", "struct_convert_args.html", null ],
    [ "countour_bench_args", "structcountour__bench__args.html", null ],
    [ "CLI::detail::element_type&lt; T, Enable &gt;", "struct_c_l_i_1_1detail_1_1element__type.html", null ],
    [ "CLI::detail::element_type&lt; T, typename std::enable_if&lt; is_copyable_ptr&lt; T &gt;::value &gt;::type &gt;", "struct_c_l_i_1_1detail_1_1element__type_3_01_t_00_01typename_01std_1_1enable__if_3_01is__copyablcf4068753293666f52fa2143458d7e20.html", null ],
    [ "CLI::detail::element_value_type&lt; T &gt;", "struct_c_l_i_1_1detail_1_1element__value__type.html", null ],
    [ "std::false_type", null, [
      [ "CLI::detail::is_mutable_container< T, conditional_t< false, void_t< typename T::value_type, decltype(std::declval< T >().end()), decltype(std::declval< T >().clear()), decltype(std::declval< T >().insert(std::declval< decltype(std::declval< T >().end())>(), std::declval< const typename T::value_type & >()))>, void > >", "struct_c_l_i_1_1detail_1_1is__mutable__container_3_01_t_00_01conditional__t_3_01false_00_01void_9711c92f16061f5742bb50eefb1b0c0c.html", null ],
      [ "CLI::detail::is_readable_container< T, conditional_t< false, void_t< decltype(std::declval< T >().end()), decltype(std::declval< T >().begin())>, void > >", "struct_c_l_i_1_1detail_1_1is__readable__container_3_01_t_00_01conditional__t_3_01false_00_01void1b163ef1438ddc3089d5e11b3b2b1293.html", null ],
      [ "CLI::detail::is_wrapper< T, conditional_t< false, void_t< typename T::value_type >, void > >", "struct_c_l_i_1_1detail_1_1is__wrapper_3_01_t_00_01conditional__t_3_01false_00_01void__t_3_01type256f69b9a9ada1608beb2e1e7b0f6f4c.html", null ],
      [ "CLI::detail::pair_adaptor< T, conditional_t< false, void_t< typename T::value_type::first_type, typename T::value_type::second_type >, void > >", "struct_c_l_i_1_1detail_1_1pair__adaptor_3_01_t_00_01conditional__t_3_01false_00_01void__t_3_01ty57376c4a6f008b828f6707df132586d8.html", null ],
      [ "CLI::is_bool< bool >", "struct_c_l_i_1_1is__bool_3_01bool_01_4.html", null ],
      [ "CLI::is_shared_ptr< const std::shared_ptr< T > >", "struct_c_l_i_1_1is__shared__ptr_3_01const_01std_1_1shared__ptr_3_01_t_01_4_01_4.html", null ],
      [ "CLI::is_shared_ptr< std::shared_ptr< T > >", "struct_c_l_i_1_1is__shared__ptr_3_01std_1_1shared__ptr_3_01_t_01_4_01_4.html", null ],
      [ "CLI::detail::is_mutable_container< T, _ >", "struct_c_l_i_1_1detail_1_1is__mutable__container.html", null ],
      [ "CLI::detail::is_readable_container< T, _ >", "struct_c_l_i_1_1detail_1_1is__readable__container.html", null ],
      [ "CLI::detail::is_wrapper< T, _ >", "struct_c_l_i_1_1detail_1_1is__wrapper.html", null ],
      [ "CLI::detail::pair_adaptor< T, _ >", "struct_c_l_i_1_1detail_1_1pair__adaptor.html", null ],
      [ "CLI::is_bool< T >", "struct_c_l_i_1_1is__bool.html", null ],
      [ "CLI::is_shared_ptr< T >", "struct_c_l_i_1_1is__shared__ptr.html", null ]
    ] ],
    [ "CLI::FormatterBase", "class_c_l_i_1_1_formatter_base.html", [
      [ "CLI::Formatter", "class_c_l_i_1_1_formatter.html", null ],
      [ "CLI::FormatterLambda", "class_c_l_i_1_1_formatter_lambda.html", null ]
    ] ],
    [ "GFA", "class_g_f_a.html", null ],
    [ "CLI::detail::has_find&lt; C, V &gt;", "struct_c_l_i_1_1detail_1_1has__find.html", null ],
    [ "heatmap_t", "structheatmap__t.html", null ],
    [ "IndexArgs", "struct_index_args.html", null ],
    [ "CLI::detail::is_complex&lt; T &gt;", "class_c_l_i_1_1detail_1_1is__complex.html", null ],
    [ "CLI::is_copyable_ptr&lt; T &gt;", "struct_c_l_i_1_1is__copyable__ptr.html", null ],
    [ "CLI::detail::is_direct_constructible&lt; T, C &gt;", "class_c_l_i_1_1detail_1_1is__direct__constructible.html", null ],
    [ "CLI::detail::is_istreamable&lt; T, S &gt;", "class_c_l_i_1_1detail_1_1is__istreamable.html", null ],
    [ "CLI::adl_detail::is_lexical_castable&lt; T, S &gt;", "class_c_l_i_1_1adl__detail_1_1is__lexical__castable.html", null ],
    [ "CLI::detail::is_ostreamable&lt; T, S &gt;", "class_c_l_i_1_1detail_1_1is__ostreamable.html", null ],
    [ "CLI::detail::is_tuple_like&lt; S &gt;", "class_c_l_i_1_1detail_1_1is__tuple__like.html", null ],
    [ "CLI::IsMemberType&lt; T &gt;", "struct_c_l_i_1_1_is_member_type.html", null ],
    [ "CLI::IsMemberType&lt; const char * &gt;", "struct_c_l_i_1_1_is_member_type_3_01const_01char_01_5_01_4.html", null ],
    [ "ksw_extz_t", "structksw__extz__t.html", null ],
    [ "linear_penalties_t", "structlinear__penalties__t.html", null ],
    [ "LinksSet", "class_links_set.html", null ],
    [ "CLI::make_void&lt; Ts &gt;", "struct_c_l_i_1_1make__void.html", null ],
    [ "match_function_params_t", "structmatch__function__params__t.html", null ],
    [ "MergeArgs", "struct_merge_args.html", null ],
    [ "Minimizer", "class_minimizer.html", null ],
    [ "MinimizerSet", "class_minimizer_set.html", null ],
    [ "mm_allocator_reference_t", "structmm__allocator__reference__t.html", null ],
    [ "mm_allocator_request_t", "structmm__allocator__request__t.html", null ],
    [ "mm_allocator_segment_t", "structmm__allocator__segment__t.html", null ],
    [ "mm_allocator_t", "structmm__allocator__t.html", null ],
    [ "mm_malloc_request_t", "structmm__malloc__request__t.html", null ],
    [ "mm_stack_segment_t", "structmm__stack__segment__t.html", null ],
    [ "mm_stack_state_t", "structmm__stack__state__t.html", null ],
    [ "mm_stack_t", "structmm__stack__t.html", null ],
    [ "CLI::OptionBase&lt; CRTP &gt;", "class_c_l_i_1_1_option_base.html", null ],
    [ "CLI::OptionBase&lt; Option &gt;", "class_c_l_i_1_1_option_base.html", [
      [ "CLI::Option", "class_c_l_i_1_1_option.html", null ]
    ] ],
    [ "CLI::OptionBase&lt; OptionDefaults &gt;", "class_c_l_i_1_1_option_base.html", [
      [ "CLI::OptionDefaults", "class_c_l_i_1_1_option_defaults.html", null ]
    ] ],
    [ "Path", "class_path.html", null ],
    [ "pcigar_op_t", "structpcigar__op__t.html", null ],
    [ "profiler_counter_t", "structprofiler__counter__t.html", null ],
    [ "profiler_rcounter_t", "structprofiler__rcounter__t.html", null ],
    [ "profiler_timer_t", "structprofiler__timer__t.html", null ],
    [ "std::runtime_error", null, [
      [ "CLI::Error", "class_c_l_i_1_1_error.html", [
        [ "CLI::ConstructionError", "class_c_l_i_1_1_construction_error.html", [
          [ "CLI::BadNameString", "class_c_l_i_1_1_bad_name_string.html", null ],
          [ "CLI::IncorrectConstruction", "class_c_l_i_1_1_incorrect_construction.html", null ],
          [ "CLI::OptionAlreadyAdded", "class_c_l_i_1_1_option_already_added.html", null ]
        ] ],
        [ "CLI::OptionNotFound", "class_c_l_i_1_1_option_not_found.html", null ],
        [ "CLI::ParseError", "class_c_l_i_1_1_parse_error.html", [
          [ "CLI::ArgumentMismatch", "class_c_l_i_1_1_argument_mismatch.html", null ],
          [ "CLI::ConfigError", "class_c_l_i_1_1_config_error.html", null ],
          [ "CLI::ConversionError", "class_c_l_i_1_1_conversion_error.html", null ],
          [ "CLI::ExcludesError", "class_c_l_i_1_1_excludes_error.html", null ],
          [ "CLI::ExtrasError", "class_c_l_i_1_1_extras_error.html", null ],
          [ "CLI::FileError", "class_c_l_i_1_1_file_error.html", null ],
          [ "CLI::HorribleError", "class_c_l_i_1_1_horrible_error.html", null ],
          [ "CLI::InvalidError", "class_c_l_i_1_1_invalid_error.html", null ],
          [ "CLI::RequiredError", "class_c_l_i_1_1_required_error.html", null ],
          [ "CLI::RequiresError", "class_c_l_i_1_1_requires_error.html", null ],
          [ "CLI::RuntimeError", "class_c_l_i_1_1_runtime_error.html", null ],
          [ "CLI::Success", "class_c_l_i_1_1_success.html", [
            [ "CLI::CallForAllHelp", "class_c_l_i_1_1_call_for_all_help.html", null ],
            [ "CLI::CallForHelp", "class_c_l_i_1_1_call_for_help.html", null ],
            [ "CLI::CallForVersion", "class_c_l_i_1_1_call_for_version.html", null ]
          ] ],
          [ "CLI::ValidationError", "class_c_l_i_1_1_validation_error.html", null ]
        ] ]
      ] ]
    ] ],
    [ "score_matrix_t", "structscore__matrix__t.html", null ],
    [ "Segment", "class_segment.html", null ],
    [ "seq_error_t", "structseq__error__t.html", null ],
    [ "sequence_buffer_t", "structsequence__buffer__t.html", null ],
    [ "sequence_offset_t", "structsequence__offset__t.html", null ],
    [ "CLI::detail::subtype_count&lt; T &gt;", "struct_c_l_i_1_1detail_1_1subtype__count.html", null ],
    [ "CLI::detail::subtype_count_min&lt; T &gt;", "struct_c_l_i_1_1detail_1_1subtype__count__min.html", null ],
    [ "std::true_type", null, [
      [ "CLI::detail::is_readable_container< T, conditional_t< false, void_t< decltype(std::declval< T >().end()), decltype(std::declval< T >().begin())>, void > >", "struct_c_l_i_1_1detail_1_1is__readable__container_3_01_t_00_01conditional__t_3_01false_00_01void1b163ef1438ddc3089d5e11b3b2b1293.html", null ],
      [ "CLI::detail::is_wrapper< T, conditional_t< false, void_t< typename T::value_type >, void > >", "struct_c_l_i_1_1detail_1_1is__wrapper_3_01_t_00_01conditional__t_3_01false_00_01void__t_3_01type256f69b9a9ada1608beb2e1e7b0f6f4c.html", null ],
      [ "CLI::detail::pair_adaptor< T, conditional_t< false, void_t< typename T::value_type::first_type, typename T::value_type::second_type >, void > >", "struct_c_l_i_1_1detail_1_1pair__adaptor_3_01_t_00_01conditional__t_3_01false_00_01void__t_3_01ty57376c4a6f008b828f6707df132586d8.html", null ],
      [ "CLI::is_bool< bool >", "struct_c_l_i_1_1is__bool_3_01bool_01_4.html", null ],
      [ "CLI::is_shared_ptr< const std::shared_ptr< T > >", "struct_c_l_i_1_1is__shared__ptr_3_01const_01std_1_1shared__ptr_3_01_t_01_4_01_4.html", null ],
      [ "CLI::is_shared_ptr< std::shared_ptr< T > >", "struct_c_l_i_1_1is__shared__ptr_3_01std_1_1shared__ptr_3_01_t_01_4_01_4.html", null ]
    ] ],
    [ "CLI::detail::type_count&lt; T, Enable &gt;", "struct_c_l_i_1_1detail_1_1type__count.html", null ],
    [ "CLI::detail::type_count&lt; T, typename std::enable_if&lt; is_complex&lt; T &gt;::value &gt;::type &gt;", "struct_c_l_i_1_1detail_1_1type__count_3_01_t_00_01typename_01std_1_1enable__if_3_01is__complex_31fac009dcf70627e04f80462c5d88ca8.html", null ],
    [ "CLI::detail::type_count&lt; T, typename std::enable_if&lt; is_mutable_container&lt; T &gt;::value &gt;::type &gt;", "struct_c_l_i_1_1detail_1_1type__count_3_01_t_00_01typename_01std_1_1enable__if_3_01is__mutable__cb200eb27fab347649b083951e77032e.html", null ],
    [ "CLI::detail::type_count&lt; T, typename std::enable_if&lt; is_wrapper&lt; T &gt;::value &amp;&amp;!is_complex&lt; T &gt;::value &amp;&amp;!is_tuple_like&lt; T &gt;::value &amp;&amp;!is_mutable_container&lt; T &gt;::value &gt;::type &gt;", "struct_c_l_i_1_1detail_1_1type__count_3_01_t_00_01typename_01std_1_1enable__if_3_01is__wrapper_39a4e337a2aa393bb8556b7ab15846b8b.html", null ],
    [ "CLI::detail::type_count&lt; T, typename std::enable_if&lt;!is_wrapper&lt; T &gt;::value &amp;&amp;!is_tuple_like&lt; T &gt;::value &amp;&amp;!is_complex&lt; T &gt;::value &amp;&amp;!std::is_void&lt; T &gt;::value &gt;::type &gt;", "struct_c_l_i_1_1detail_1_1type__count_3_01_t_00_01typename_01std_1_1enable__if_3_9is__wrapper_3_b01f5ffbc1be4715e41384ef05a4c2a6.html", null ],
    [ "CLI::detail::type_count_base&lt; T, Enable &gt;", "struct_c_l_i_1_1detail_1_1type__count__base.html", null ],
    [ "CLI::detail::type_count_base&lt; T, typename std::enable_if&lt; is_mutable_container&lt; T &gt;::value &gt;::type &gt;", "struct_c_l_i_1_1detail_1_1type__count__base_3_01_t_00_01typename_01std_1_1enable__if_3_01is__mut25537d1dbe2209c0fb1d9a95e46a36a7.html", null ],
    [ "CLI::detail::type_count_base&lt; T, typename std::enable_if&lt; is_tuple_like&lt; T &gt;::value &amp;&amp;!is_mutable_container&lt; T &gt;::value &gt;::type &gt;", "struct_c_l_i_1_1detail_1_1type__count__base_3_01_t_00_01typename_01std_1_1enable__if_3_01is__tup573c8f6a452dc2b871d7cd3189dda714.html", null ],
    [ "CLI::detail::type_count_base&lt; T, typename std::enable_if&lt;!is_tuple_like&lt; T &gt;::value &amp;&amp;!is_mutable_container&lt; T &gt;::value &amp;&amp;!std::is_void&lt; T &gt;::value &gt;::type &gt;", "struct_c_l_i_1_1detail_1_1type__count__base_3_01_t_00_01typename_01std_1_1enable__if_3_9is__tupl1d95856913595d9d18df1e9b7db10a2c.html", null ],
    [ "CLI::Validator", "class_c_l_i_1_1_validator.html", [
      [ "CLI::AsNumberWithUnit", "class_c_l_i_1_1_as_number_with_unit.html", [
        [ "CLI::AsSizeValue", "class_c_l_i_1_1_as_size_value.html", null ]
      ] ],
      [ "CLI::Bound", "class_c_l_i_1_1_bound.html", null ],
      [ "CLI::CheckedTransformer", "class_c_l_i_1_1_checked_transformer.html", null ],
      [ "CLI::CustomValidator", "class_c_l_i_1_1_custom_validator.html", null ],
      [ "CLI::FileOnDefaultPath", "class_c_l_i_1_1_file_on_default_path.html", null ],
      [ "CLI::IsMember", "class_c_l_i_1_1_is_member.html", null ],
      [ "CLI::Range", "class_c_l_i_1_1_range.html", null ],
      [ "CLI::Transformer", "class_c_l_i_1_1_transformer.html", null ],
      [ "CLI::TypeValidator< DesiredType >", "class_c_l_i_1_1_type_validator.html", null ],
      [ "CLI::detail::EscapedStringTransformer", "class_c_l_i_1_1detail_1_1_escaped_string_transformer.html", null ],
      [ "CLI::detail::ExistingDirectoryValidator", "class_c_l_i_1_1detail_1_1_existing_directory_validator.html", null ],
      [ "CLI::detail::ExistingFileValidator", "class_c_l_i_1_1detail_1_1_existing_file_validator.html", null ],
      [ "CLI::detail::ExistingPathValidator", "class_c_l_i_1_1detail_1_1_existing_path_validator.html", null ],
      [ "CLI::detail::IPV4Validator", "class_c_l_i_1_1detail_1_1_i_p_v4_validator.html", null ],
      [ "CLI::detail::NonexistentPathValidator", "class_c_l_i_1_1detail_1_1_nonexistent_path_validator.html", null ]
    ] ],
    [ "vector_t", "structvector__t.html", null ],
    [ "ViewArgs", "struct_view_args.html", null ],
    [ "Walk", "class_walk.html", null ],
    [ "wavefront_align_status_t", "structwavefront__align__status__t.html", null ],
    [ "wavefront_aligner_attr_t", "structwavefront__aligner__attr__t.html", null ],
    [ "wavefront_bialigner_t", "structwavefront__bialigner__t.html", null ],
    [ "wavefront_components_t", "structwavefront__components__t.html", null ],
    [ "wavefront_heuristic_t", "structwavefront__heuristic__t.html", null ],
    [ "wavefront_penalties_t", "structwavefront__penalties__t.html", null ],
    [ "wavefront_plot_attr_t", "structwavefront__plot__attr__t.html", null ],
    [ "wavefront_plot_t", "structwavefront__plot__t.html", null ],
    [ "wavefront_pos_t", "structwavefront__pos__t.html", null ],
    [ "wavefront_sequences_t", "structwavefront__sequences__t.html", null ],
    [ "wavefront_set_t", "structwavefront__set__t.html", null ],
    [ "wavefront_slab_t", "structwavefront__slab__t.html", null ],
    [ "wavefront_t", "structwavefront__t.html", null ],
    [ "wf_backtrace_buffer_t", "structwf__backtrace__buffer__t.html", null ],
    [ "wf_backtrace_init_pos_t", "structwf__backtrace__init__pos__t.html", null ],
    [ "wf_bialign_breakpoint_t", "structwf__bialign__breakpoint__t.html", null ],
    [ "wfa::WFAligner", "classwfa_1_1_w_f_aligner.html", [
      [ "wfa::WFAlignerEdit", "classwfa_1_1_w_f_aligner_edit.html", null ],
      [ "wfa::WFAlignerGapAffine", "classwfa_1_1_w_f_aligner_gap_affine.html", null ],
      [ "wfa::WFAlignerGapAffine2Pieces", "classwfa_1_1_w_f_aligner_gap_affine2_pieces.html", null ],
      [ "wfa::WFAlignerGapLinear", "classwfa_1_1_w_f_aligner_gap_linear.html", null ],
      [ "wfa::WFAlignerIndel", "classwfa_1_1_w_f_aligner_indel.html", null ]
    ] ],
    [ "CLI::detail::wrapped_type&lt; T, def, Enable &gt;", "struct_c_l_i_1_1detail_1_1wrapped__type.html", null ],
    [ "CLI::detail::wrapped_type&lt; T, def, typename std::enable_if&lt; is_wrapper&lt; T &gt;::value &gt;::type &gt;", "struct_c_l_i_1_1detail_1_1wrapped__type_3_01_t_00_01def_00_01typename_01std_1_1enable__if_3_01isa724b5b3d1f263241cafc27a49bae246.html", null ]
];